name: 'Run Bazel Command'
description: 'Sets up Bazel with caching and runs Bazel command'
inputs:
    bazel-command:
        description: 'The bazel command to run. Typically the arguments after bazelisk'
        required: true
    cache-key:
        description: 'The cache key to uniquely identify this build'
        required: true
runs:
    using: "composite"
    steps:
        - name: Setup Bazel
          uses: bazel-contrib/setup-bazel@0.16.0
          with:
              bazelisk-cache: true
              disk-cache: ${{ inputs.cache-key }}
              repository-cache: true

        - name: Install JDK 17
          uses: actions/setup-java@v5
          with:
              distribution: "zulu"
              java-version: "17"

        - name: Setup Android SDK
          uses: ./.github/actions/android

        - name: Run bazel command
          shell: bash
          run: bazelisk ${{ inputs.bazel-command }} --config=ci
