name: 'Run Bazel Command'
description: 'Ensures bazelisk, mounts Bazel Cache from artifacts and runs Bazel command'
inputs:
    bazel-command:
        description: 'The bazel command to run. Typically the arguments after bazelisk'
        required: true
    cache-key:
        description: 'The cache key to uniquely identify this build'
        required: true
runs:
    using: "composite"
    steps:
        -   name: Set Bazel version
            shell: bash
            run: echo "USE_BAZEL_VERSION=$(cat .bazelversion)" >> $GITHUB_ENV

        -   name: Setup Bazelisk
            uses: bazelbuild/setup-bazelisk@v3
        -   name: Install JDK 17
            uses: actions/setup-java@v4
            with:
                distribution: "zulu"
                java-version: "17"

        -   name: Setup Android SDK
            uses: ./.github/actions/android

        -   name: Mount bazel cache
            uses: actions/cache@v4
            with:
                path: "bazel-cache"
                key: ${{ inputs.cache-key }}

        -   name: Run bazel command
            shell: bash
            run: bazelisk ${{ inputs.bazel-command }} --config=ci