name: 'Setup Android SDK'
description: 'Installs Android SDK and necessary components for CI builds'
runs:
  using: "composite"
  steps:
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        accept-android-sdk-licenses: 'true'
        log-accepted-android-sdk-licenses: 'false'
        packages: 'platforms;android-34 build-tools;33.0.1 ndk;23.0.7599858 tools platform-tools'
    - name: Add NDK to PATH
      shell: bash
      run: |
        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/23.0.7599858" >> $GITHUB_ENV
        echo "$ANDROID_HOME/ndk/23.0.7599858" >> $GITHUB_PATH