/*
 * Copyright 2026 Grabtaxi Holdings PTE LTD (GRAB)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.grab.grazel.migrate.dependencies

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

internal object RulesJvmExternalLockfileRenderer {
    fun render(lockfile: RulesJvmExternalLockfile): String {
        val lines = mutableListOf(
            "{",
            """  "__AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_FILE_MANUALLY": "THERE_IS_NO_DATA_ONLY_ZUUL",""",
            """  "$INPUT_ARTIFACTS_HASH_KEY": ${jsonEncodeIndent(lockfile.inputArtifactsHash, prefix = "  ")},""",
            """  "$RESOLVED_ARTIFACTS_HASH_KEY": ${jsonEncodeIndent(lockfile.resolvedArtifactsHash, prefix = "  ")},""",
        )
        lockfile.conflictResolution?.takeIf(::isNonEmptyContainer)?.let { conflictResolution ->
            lines += """  "conflict_resolution": ${jsonEncodeIndent(conflictResolution, prefix = "  ")},"""
        }
        lines += """  "artifacts": ${jsonEncodeIndent(lockfile.artifacts, prefix = "  ")},"""
        lines += """  "dependencies": ${jsonEncodeIndent(lockfile.dependencies, prefix = "  ")},"""
        if (lockfile.m2local) {
            lines += """  "m2local": true,"""
        }
        lines += """  "packages": ${jsonEncodeIndent(lockfile.packages, prefix = "  ")},"""
        lines += """  "repositories": {"""
        val repositories = lockfile.repositories.entries.toList()
        repositories.forEachIndexed { index, (repository, artifacts) ->
            val suffix = if (index == repositories.lastIndex) "" else ","
            lines += """    ${rjeJsonString(repository)}: ${jsonEncodeIndent(artifacts, prefix = "    ")}$suffix"""
        }
        lines += "  },"
        lines += """  "services": ${jsonEncodeIndent(lockfile.services, prefix = "  ")},"""
        lockfile.skipped?.takeIf(::isNonEmptyContainer)?.let { skipped ->
            lines += """  "skipped": ${jsonEncodeIndent(skipped, prefix = "  ")},"""
        }
        lines += """  "version": "${lockfile.version}""""
        lines += "}"
        lines += ""
        return lines.joinToString("\n")
    }

    private fun isNonEmptyContainer(element: JsonElement): Boolean =
        when (element) {
            is JsonArray -> element.isNotEmpty()
            is JsonObject -> element.isNotEmpty()
            else -> true
        }

    private fun jsonEncodeIndent(element: JsonElement, prefix: String): String {
        return when (element) {
            is JsonObject -> {
                if (element.isEmpty()) return "{}"
                val childPrefix = "$prefix  "
                element.entries
                    .sortedBy { (key, _) -> key }
                    .joinToString(
                        separator = ",\n",
                        prefix = "{\n",
                        postfix = "\n$prefix}"
                    ) { (key, value) ->
                        "$childPrefix${rjeJsonString(key)}: ${jsonEncodeIndent(value, childPrefix)}"
                    }
            }

            is JsonArray -> {
                if (element.isEmpty()) return "[]"
                val childPrefix = "$prefix  "
                element.joinToString(
                    separator = ",\n",
                    prefix = "[\n",
                    postfix = "\n$prefix]"
                ) { value -> "$childPrefix${jsonEncodeIndent(value, childPrefix)}" }
            }

            is JsonPrimitive -> when {
                element is JsonNull -> "null"
                element.isString -> rjeJsonString(element.content)
                else -> element.content
            }

            JsonNull -> "null"
        }
    }
}
