name: 'Run Gradle with Cache'
description: 'Configures Gradle environment with JDK, Android SDK, and cache setup'
inputs:
  job-id:
    description: 'Unique identifier for the cache (kept for compatibility, not used)'
    required: true
  arguments:
    description: 'Gradle command arguments to execute'
    required: true
  build-root-directory:
    description: 'Root directory of the Gradle project'
    default: '.'
  read-only:
    description: 'Whether to use read-only cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: "zulu"
        java-version: "17"

    - name: Setup Android SDK
      uses: ./.github/actions/android

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-read-only: ${{ inputs.read-only }}
        build-root-directory: ${{ inputs.build-root-directory }}

    - name: Run Gradle
      shell: bash
      working-directory: ${{ inputs.build-root-directory }}
      run: ./gradlew ${{ inputs.arguments }}
