load("@grab_bazel_common//rules:defs.bzl", "android_library")

android_library(
    name = "sample-android-test-util-debug",
    srcs = glob([
        "src/main/java/com/grab/grazel/android/sample/testutil/TestUtil.kt",
    ]),
    custom_package = "com.grab.grazel.android.sample.testutil",
    lint_options = {
        "enabled": True,
        "config": "//:lint.xml",
    },
    manifest = "src/main/AndroidManifest.xml",
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//sample-android-test-util-dep:sample-android-test-util-dep-debug",
        "@maven//:com_squareup_moshi_moshi",
    ],
)
