/*
 * Copyright 2026 Grabtaxi Holdings PTE LTD (GRAB)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.grab.grazel.migrate.dependencies

import com.google.common.truth.Truth.assertThat
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import org.junit.Test

class RulesJvmExternalLockfileRendererTest {

    @Test
    fun `renders rje lockfile with stable top level order and omits empty optional sections`() {
        val lockfile = RulesJvmExternalLockfile(
            inputArtifactsHash = JsonObject(
                linkedMapOf(
                    "com.example:lib" to JsonPrimitive(1),
                    "repositories" to JsonPrimitive(2)
                )
            ),
            resolvedArtifactsHash = JsonObject(
                linkedMapOf("com.example:lib" to JsonPrimitive(3))
            ),
            conflictResolution = JsonObject(emptyMap()),
            artifacts = JsonObject(
                linkedMapOf(
                    "com.example:lib" to JsonObject(
                        linkedMapOf(
                            "shasums" to JsonObject(linkedMapOf("jar" to JsonPrimitive("abc"))),
                            "version" to JsonPrimitive("1.0")
                        )
                    )
                )
            ),
            dependencies = JsonObject(linkedMapOf("com.example:lib" to JsonArray(emptyList()))),
            m2local = false,
            packages = JsonObject(linkedMapOf("com.example:lib" to JsonArray(listOf(JsonPrimitive("com.example"))))),
            repositories = JsonObject(
                linkedMapOf("https://repo.example/maven2/" to JsonArray(listOf(JsonPrimitive("com.example:lib"))))
            ),
            services = JsonObject(emptyMap()),
            skipped = JsonArray(emptyList())
        )

        assertThat(RulesJvmExternalLockfileRenderer.render(lockfile))
            .isEqualTo(
                """
                {
                  "__AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_FILE_MANUALLY": "THERE_IS_NO_DATA_ONLY_ZUUL",
                  "__INPUT_ARTIFACTS_HASH": {
                    "com.example:lib": 1,
                    "repositories": 2
                  },
                  "__RESOLVED_ARTIFACTS_HASH": {
                    "com.example:lib": 3
                  },
                  "artifacts": {
                    "com.example:lib": {
                      "shasums": {
                        "jar": "abc"
                      },
                      "version": "1.0"
                    }
                  },
                  "dependencies": {
                    "com.example:lib": []
                  },
                  "packages": {
                    "com.example:lib": [
                      "com.example"
                    ]
                  },
                  "repositories": {
                    "https://repo.example/maven2/": [
                      "com.example:lib"
                    ]
                  },
                  "services": {},
                  "version": "3"
                }

                """.trimIndent()
            )
    }
}
